### ISSUE TITLE
False positive: component can only have one instance-level <script> element

### ISSUE THREAD

**Issue by IlyaSemenov** [UnwrittenFun/prettier-plugin-svelte#30]
The following Svelte component:

```html
<script></script>

<div>
  hello!
  <script>alert(1)</script>
</div>
```

makes the plugin crash with:

```
1.svelte[error] 1.svelte: ParseError: A component can only have one instance-level <script> element
[error]     at error$1 (/Users/semenov/test/node_modules/svelte/compiler.js:13491:20)
[error]     at Parser$2.error (/Users/semenov/test/node_modules/svelte/compiler.js:13567:10)
[error]     at Object.parse$2 [as parse] (/Users/semenov/test/node_modules/svelte/compiler.js:13669:17)
[error]     at Object.parse (/Users/semenov/test/node_modules/prettier-plugin-svelte/plugin.js:532:47)
[error]     at Object.parse$2 [as parse] (/Users/semenov/test/node_modules/prettier/bin-prettier.js:10635:19)
[error]     at coreFormat (/Users/semenov/test/node_modules/prettier/bin-prettier.js:13844:23)
[error]     at format (/Users/semenov/test/node_modules/prettier/bin-prettier.js:14102:73)
[error]     at formatWithCursor (/Users/semenov/test/node_modules/prettier/bin-prettier.js:14118:12)
[error]     at Object.formatWithCursor (/Users/semenov/test/node_modules/prettier/bin-prettier.js:42529:15)
[error]     at format$1 (/Users/semenov/test/node_modules/prettier/bin-prettier.js:43898:21)
error Command failed with exit code 2.
```

However it's not the instance level script, it's perfectly valid Svelte code: https://github.com/sveltejs/svelte/issues/335

---

ALSO, the plugin will crash with the same error even if the script tag is commented!

```html
<script></script>

<div>
  hello!
  <!-- <script>alert(1)</script> -->
</div>
```

**Comment by UnwrittenFun** [comment]
hmm, that is odd given that the stack trace suggests its coming from svelte itself

**Comment by IlyaSemenov** [comment]
Do you need the reproduction repo? Yes, I saw that the error was coming from the compiler itself, but perhaps it's not the original file content that is passed to it (or passed with a wrong set of options).

**Comment by UnwrittenFun** [comment]
I suspect its this line https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/668fb44587fc8cc8f112f135400211d2483261d7/src/index.ts#L31 picking out all scripts regardless of where they are
