### ISSUE TITLE
Error: Unrecognized option 'onwarn'

### ISSUE THREAD

**Issue by beenotung** [UnwrittenFun/prettier-plugin-svelte#8]
## The Console Log
```
> svelte-app@1.0.0 format /home/beenotung/workspace/local/gcms/gcms-client
> prettier --write --plugin-search-dir=. ./src/*.{svelte,html}

src/App-bug-report.svelte
[error] src/App-bug-report.svelte: Error: Unrecognized option 'onwarn'
[error]     at Object.keys.forEach.key (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/svelte/compiler.js:23582:20)
[error]     at Array.forEach (<anonymous>)
[error]     at validate_options (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/svelte/compiler.js:23576:27)
[error]     at Object.compile (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/svelte/compiler.js:23618:6)
[error]     at parse (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier-plugin-svelte/plugin.js:501:27)
[error]     at Object.parse (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier-plugin-svelte/plugin.js:523:20)
[error]     at Object.parse$2 [as parse] (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier/bin-prettier.js:10635:19)
[error]     at coreFormat (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier/bin-prettier.js:13844:23)
[error]     at format (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier/bin-prettier.js:14103:73)
[error]     at formatWithCursor (/home/beenotung/workspace/local/gcms/gcms-client/node_modules/prettier/bin-prettier.js:14119:12)
```

## The Sample Source
```html
<script>
	export let name = 'admin';
	let databases = [];
	let databaseName = '';
	let apiEndpoint = {
	  host: 'localhost',
	  port: 3000
	};
	let apiBaseUrl = '';
	$: apiBaseUrl = 'http://' + apiEndpoint.host + ':' + apiEndpoint.port + '/admin/';

	let res;

	function checkApiResult(res){
	  let {status} = res;
	  if(!(200<=status && status<300)){
	    return res.json().then(x=>Promise.reject(x));
	  }
	  let contentType = res.headers.get('Content-Type');
	  if(contentType&&contentType.startsWith('application/json')){
	    return res.json();
	  }
	  return res;
	}
	let mockDBs = ['db1','db2'].map(name=>({name}));
	function mockFetch(url,{data}) {
	  if(url.endsWith('databases')){
	    return Promise.resolve({status:200,headers:{get:()=>'application/json'},json:()=>Promise.resolve(mockDBs)})
	  }
	  if(url.endsWith('database')){
	    mockDBs.push(data);
	    return Promise.resolve({status:201,headers:{get:()=>'text'}});
	  }
	  return Promise.resolve({status:400,headers:{get:()=>'text'},statusText:'unknown api'});
	}
	fetch = mockFetch;
	function apiCall({url,method,data}){
	  let headers = [['Content-Type','application/json']];
	  let body = JSON.stringify(data);
	  return fetch(apiBaseUrl+url,{method,body,headers})
	    .then(res=>checkApiResult(res))
	}

	function loadAllDatabases(){
	  res = apiCall({url:'databases'});
	  res.then(xs=>databases=xs);
	}
	function createDatabase(){
	  res = apiCall({
	    url:'database',
	    method: 'post',
	    data: {database:{
	      name: databaseName,
	      tables: []
	    }}
	  });
	  res.then(()=>loadAllDatabases());
	}

	function format(o) {
	  return '<pre>' + JSON.stringify(o,null,2) + '</pre>';
	}
</script>

<style>
</style>


<h2>Database</h2>
<input type="button" value="Load All Database" on:click="{loadAllDatabases}">
<h3>Database Names</h3>
<ul>
{#each databases as {name} (name)}
<li>{name}</li>
{/each}
</ul>
<p>Total number of database: {databases.length}</p>

<label for="database">New Database Name</label>
<input id="database" bind:value="{databaseName}">
<input type="button" value="Create Database" on:click="{createDatabase}">

<h2>API Result</h2>
{#await res}
waiting...
{:then result}
resolve: {@html format(result)}
{:catch error}
reject: {@html format(error)}
{/await}
```

**Comment by UnwrittenFun** [comment]
fixed by #7
