### ISSUE TITLE
Chokes on expressions in templates.

### ISSUE THREAD

**Issue by hperrin** [UnwrittenFun/prettier-plugin-svelte#90]
It seems that the plugin is not able to handle expressions in ~class attributes~ templates.

This is fine:
```html
<div class="some-class-{name}" />
```

But this causes an error:
```html
<div class="some-class-{getName()}" />
```

Tested with this:

Input:
```html
<div class="some-class-{getName()}" />

<script>
  function getName() {
    return 'name';
  }
</script>
```

Output:
```
packages/countdown/test.svelte{
    "type": "CallExpression",
    "start": 24,
    "end": 33,
    "loc": {
        "start": {
            "line": 1,
            "column": 24
        },
        "end": {
            "line": 1,
            "column": 33
        }
    },
    "callee": {
        "type": "Identifier",
        "start": 24,
        "end": 31,
        "loc": {
            "start": {
                "line": 1,
                "column": 24
            },
            "end": {
                "line": 1,
                "column": 31
            }
        },
        "name": "getName"
    },
    "arguments": [],
    "isJS": true
}

[error] packages/countdown/test.svelte: Error: unknown node type: CallExpression
[error]     at Object.print (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:446:11)
[error]     at callPluginPrintFunction (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14613:18)
[error]     at /Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:47
[error]     at Object.printComments (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14236:19)
[error]     at printGenerically (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:22)
[error]     at FastPath.call (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14356:20)
[error]     at printJS (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:557:17)
[error]     at Object.print (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:257:33)
[error]     at callPluginPrintFunction (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14613:18)
[error]     at /Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:47
```

**Comment by hperrin** [comment]
Seems this is also a problem in style attributes.

**Comment by hperrin** [comment]
Make that all attributes.

**Comment by hperrin** [comment]
Not even just attributes. It can't handle expressions in `{}` at all.

**Comment by hperrin** [comment]
Tested with some code from the Svelte example docs:

```html
{a + b}

<script>
  const a = 1;
  const b = 1;
</script>
```

Output:
```
packages/countdown/test.svelte{
    "type": "BinaryExpression",
    "start": 1,
    "end": 6,
    "loc": {
        "start": {
            "line": 1,
            "column": 1
        },
        "end": {
            "line": 1,
            "column": 6
        }
    },
    "left": {
        "type": "Identifier",
        "start": 1,
        "end": 2,
        "loc": {
            "start": {
                "line": 1,
                "column": 1
            },
            "end": {
                "line": 1,
                "column": 2
            }
        },
        "name": "a"
    },
    "operator": "+",
    "right": {
        "type": "Identifier",
        "start": 5,
        "end": 6,
        "loc": {
            "start": {
                "line": 1,
                "column": 5
            },
            "end": {
                "line": 1,
                "column": 6
            }
        },
        "name": "b"
    },
    "isJS": true
}

[error] packages/countdown/test.svelte: Error: unknown node type: BinaryExpression
[error]     at Object.print (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:446:11)
[error]     at callPluginPrintFunction (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14613:18)
[error]     at /Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:47
[error]     at Object.printComments (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14236:19)
[error]     at printGenerically (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:22)
[error]     at FastPath.call (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14356:20)
[error]     at printJS (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:557:17)
[error]     at Object.print (/Users/hperrin/repos/pnotify/node_modules/prettier-plugin-svelte/plugin.js:257:33)
[error]     at callPluginPrintFunction (/Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14613:18)
[error]     at /Users/hperrin/repos/pnotify/node_modules/prettier/bin-prettier.js:14563:47
```

**Comment by hperrin** [comment]
Am I doing something wrong? This seems very basic.

**Comment by hperrin** [comment]
Oh I see, this is a duplicate of #84. I'll close it.

**Comment by Acidic9** [comment]
#84 is not about BinaryExpression though. I am also experiencing this issue.
